version: '3.8'

services:
  php:
    volumes:
      - ../web:/var/www/html
      - ../php:/var/www/php
      - ../etc/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ../web:/var/www/html
      - ../etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../etc/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - php

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
